package org.dieschnittstelle.jee.esa.jws4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-12-02T11:24:37.596+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://jws4.esa.jee.dieschnittstelle.org/", name = "ProductCRUDWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductCRUDWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "readAllProducts", targetNamespace = "http://jws4.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.jws4.ReadAllProducts")
    @WebMethod
    @ResponseWrapper(localName = "readAllProductsResponse", targetNamespace = "http://jws4.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.jws4.ReadAllProductsResponse")
    public java.util.List<org.dieschnittstelle.jee.esa.jws4.AbstractProduct> readAllProducts();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://jws4.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.jws4.CreateProduct")
    @WebMethod
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://jws4.esa.jee.dieschnittstelle.org/", className = "org.dieschnittstelle.jee.esa.jws4.CreateProductResponse")
    public org.dieschnittstelle.jee.esa.jws4.AbstractProduct createProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dieschnittstelle.jee.esa.jws4.AbstractProduct arg0
    );
}
